name: CD

on:
  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

permissions:
  contents: write
  packages: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-freebsd, build-netbsd]

    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          release_notes_file: RELEASE_NOTES.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          tag_name: ${{ github.ref }}
          body_path: RELEASE_NOTES.md
          files: mommy-*.*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt install -y build-essential gzip libarchive-tools rpm rubygems squashfs-tools
          sudo gem install --no-document fpm
      - name: Build executable
        run: ./build.sh apk deb rpm pacman tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/mommy-*.*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install fpm
        run: sudo gem install --no-document fpm
      - name: Build executable
        run: ./build.sh osxpkg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/mommy-*.*

  build-freebsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install fpm && Build executable
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y bash git devel/ruby-gems
            gem install --no-document fpm

            # Workaround for https://github.com/jordansissel/fpm/pull/1922
            pkg install -y gtar
            mv /usr/bin/tar /usr/bin/bsdtar
            mv /usr/local/bin/gtar /usr/bin/tar

            # Ignore ownership issues
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
          run: ./build.sh freebsd
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/mommy-*.*

  build-netbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install fpm && Build executable
        uses: vmactions/netbsd-vm@v0
        with:
          usesh: true
          prepare: |
            # Install Ruby and gems
            pkg_add pkgin
            pkgin -y install bsdtar curl git ruby31
            curl https://rubygems.org/rubygems/rubygems-3.4.7.zip > rubygems.zip
            mkdir rubygems
            bsdtar --strip-components=1 -x -C rubygems -f rubygems.zip
            cd rubygems
            ruby31 setup.rb
            cd ../

            # Install fpm
            gem install --no-document fpm

            # Ignore ownership issues
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
          run: PATH="/sbin:/usr/sbin:/usr/pkg/sbin:/usr/local/sbin:$PATH" ./build.sh pkgin
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/mommy-*.*
