name: CI

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellSpec
        run: |
          git clone https://github.com/shellspec/shellspec.git "$HOME/shellspec/"
          echo "$HOME/shellspec" >> $GITHUB_PATH
      - name: Run tests
        run: ./test.sh

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellSpec
        run: |
          git clone https://github.com/shellspec/shellspec.git "$HOME/shellspec/"
          echo "$HOME/shellspec" >> $GITHUB_PATH
      - name: Run tests
        run: ./test.sh

  test-freebsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellSpec && Run tests
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install -y git
            git clone https://github.com/shellspec/shellspec.git "$HOME/shellspec/"
          run: PATH="$HOME/shellspec:$PATH" ./test.sh

  test-netbsd:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellSpec && Run tests
        uses: vmactions/netbsd-vm@v0
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg_add pkgin
            pkgin -y install git
            git clone https://github.com/shellspec/shellspec.git "$HOME/shellspec/"
          run: PATH="$HOME/shellspec:$PATH" ./test.sh

  test-solaris:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellSpec && Run tests
        uses: vmactions/solaris-vm@v0
        with:
          usesh: true
          copyback: false
          prepare: |
            pkg install git
            git clone https://github.com/shellspec/shellspec.git "$HOME/shellspec/"
          run: PATH="$HOME/shellspec:$PATH" ./test.sh
